name: Y Media Labs Engineering Blog 
description: 
meta_description: "Y Media Labs Engineering Blog"

aboutPage: false

markdown: redcarpet
highlighter: pygments

exclude: [vendor]

paginate: 5
baseurl: /
domain_name: 'http://.com'
google_analytics: 
disqus: false
disqus_shortname: 

# Details for the RSS feed generator
url:            'http://.com'
author:         'YMediaLabs'
authorTwitter:  'ymedialabs'

permalink:       /blog/:year/:month/:day/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
